[project]
name = "sona"
version = "0.1.0"
description = "Desktop audio workspace with Apple Speech and Whisper model resource management"
readme = "README.md"
authors = [
    { name = "YIHANG", email = "leo.morrison.2001@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pywebview>=6.2.1",
]

[project.scripts]
sona = "sona:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
